# Generated by Django 3.1.5 on 2021-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Kayıt tarihi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='description',
            field=models.TextField(verbose_name='Ürün Tanımı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Ürün Resmi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ürün Adı'),
        ),
    ]
